/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-01-26 01:11:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sql.WebpgUtil;
import javabeans.Person;
import javabeans.Employee;

public final class ManagerProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javabeans.Employee");
    _jspx_imports_classes.add("sql.WebpgUtil");
    _jspx_imports_classes.add("javabeans.Person");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Employee Profile</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");

	System.out.println("before get session");
	Employee em = WebpgUtil.getEmployeeUser(WebpgUtil.getSession());
	System.out.println("after get session");

      out.write("\n");
      out.write("<center>\n");
      out.write("<h2 class = \"employee_title\">\n");
      out.write("Employee Profile\n");
      out.write("<h2>\n");
      out.write("</center>\n");
      out.write("<div class = \"employee_photo\" alt=\"profilePicture\">\n");
      out.write("<img src = \"p1.png\" width=\"100\" height=\"100\">\n");
      out.write("</div>\n");
      out.write("<div>\n");
      out.write("<table>\n");
      out.write("<tbody>\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t\tFirst Name:\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.getfirstName());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t\tLast Nane: \n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.getLastName());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t\tPassword: \n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.getpassword());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t\tSSN: \n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.getSSN());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t\tRole: \n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.getRole());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t\tAddress:\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.getStreet());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.getCity());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.getState());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.getzip());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t\tEmail:\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.getemail());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t\tTelephone:\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t");
      out.print(em.gettelephone());
      out.write("\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("</tbody>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ManagerUpdate.jsp\">\n");
      out.write("\t<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" placeholder=\"Edit\"></input>\n");
      out.write("</form>\n");
      out.write("As a customer-representative, you are able to:\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/MVUS\">\n");
      out.write("<p>View all users and modify their information</p>\n");
      out.write("<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" placeholder=\"View\"></input>\n");
      out.write("</form>\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VES\">\n");
      out.write("<p>View all employees and modify their information</p>\n");
      out.write("<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" placeholder=\"View\"></input>\n");
      out.write("</form>\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/salereports\">\n");
      out.write("<p>Obtain a sales report for a particular month</p>\n");
      out.write("<p>Please enter the year and month that you need want to generate a sales report</p>\n");
      out.write("Year: <input type=\"text\" class=\"btn btn-lg btn-primary btn-block\" name=\"year\" placeholder=\"year\"></input><br>\n");
      out.write("Month: <input type=\"text\" class=\"btn btn-lg btn-primary btn-block\" name=\"month\" placeholder=\"month\"><br>\n");
      out.write("<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" value=\"View\"></input>\n");
      out.write("</form>\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/datebytime\">\n");
      out.write("<p>Produce a list of date based on calendar date</p>\n");
      out.write("<p>Please enter a particular date of year</p>\n");
      out.write("Year: <input type=\"text\" class=\"btn btn-lg btn-primary btn-block\" name=\"dateyear\" placeholder=\"yyyy\"></input><br>\n");
      out.write("Month: <input type=\"text\" class=\"btn btn-lg btn-primary btn-block\" name=\"datemonth\" placeholder=\"MM\"></input><br>\n");
      out.write("Dates: <input type=\"text\" class=\"btn btn-lg btn-primary btn-block\" name=\"datedate\" placeholder=\"dd\"></input><br>\n");
      out.write("<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" value=\"View\"></input>\n");
      out.write("</form>\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/datebyname\">\n");
      out.write("<p>Produce a list of date based on provided name</p>\n");
      out.write("<p>Please enter a customer name</p>\n");
      out.write("<input type=\"text\" class=\"btn btn-lg btn-primary btn-block\" name=\"datename\" placeholder=\"eg: Tom Cat\"><br>\n");
      out.write("<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" value=\"View\"></input>\n");
      out.write("</form>\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/revenuebytime\">\n");
      out.write("<p>Produce a list of revenue based on provided name</p>\n");
      out.write("<p>Please enter a particular day</p>\n");
      out.write("Year: <input type=\"text\" class=\"btn btn-lg btn-primary btn-block\" name=\"ryear\" placeholder=\"yyyy\"></input><br>\n");
      out.write("Month: <input type=\"text\" class=\"btn btn-lg btn-primary btn-block\" name=\"rmonth\" placeholder=\"MM\"></input><br>\n");
      out.write("Dates: <input type=\"text\" class=\"btn btn-lg btn-primary btn-block\" name=\"rdate\" placeholder=\"dd\"></input><br>\n");
      out.write("<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" value=\"View\"></input>\n");
      out.write("</form>\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/revenuebyname\">\n");
      out.write("<p>Produce a list of revenue based on provided name</p>\n");
      out.write("<p>Please enter a customer name</p>\n");
      out.write("<input type=\"text\" class=\"btn btn-lg btn-primary btn-block\" name=\"revenuename\" placeholder=\"eg: Tom Cat\"><br>\n");
      out.write("<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" value=\"View\"></input>\n");
      out.write("</form>\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/revenueCR\">\n");
      out.write("<p>Produce a customer representative who generated the most revenue in total</p>\n");
      out.write("<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" value=\"View\"></input>\n");
      out.write("</form>\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/revenueCus\">\n");
      out.write("<p>Produce a customer who generated the most revenue in total</p>\n");
      out.write("<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" value=\"View\"></input>\n");
      out.write("</form>\n");
      out.write("<form method = \"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/revenueCus\">\n");
      out.write("<p>Produce a list of most active customers</p>\n");
      out.write("<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" value=\"View\"></input>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
