/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-01-29 21:44:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utilServlet.inputValidate;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utilServlet.inputValidate");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>User Sign Up</title>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction handleCheck(){\n");
      out.write("\t\tvar able = document.getElementById(\"registered\").checked;\n");
      out.write("\t\tif (able == true){\n");
      out.write("\t\t\tdocument.getElementById(\"fname\").disabled = true;\n");
      out.write("\t\t\tdocument.getElementById(\"lname\").disabled = true;\n");
      out.write("\t\t\tdocument.getElementById(\"street\").disabled = true;\n");
      out.write("\t\t\tdocument.getElementById(\"city\").disabled = true;\n");
      out.write("\t\t\tdocument.getElementById(\"state\").disabled = true;\n");
      out.write("\t\t\tdocument.getElementById(\"zipcode\").disabled = true;\n");
      out.write("\t\t\tdocument.getElementById(\"email\").disabled = true;\n");
      out.write("\t\t\tdocument.getElementById(\"telephone\").disabled = true;\n");
      out.write("\t\t\tdocument.getElementById(\"registered\").value = \"yes\";\n");
      out.write("\t\t}\n");
      out.write("\t\telse{\n");
      out.write("\t\t\t//set value to able\n");
      out.write("\t\t\tdocument.getElementById(\"fname\").disabled = false;\n");
      out.write("\t\t\tdocument.getElementById(\"lname\").disabled = false;\n");
      out.write("\t\t\tdocument.getElementById(\"street\").disabled = false;\n");
      out.write("\t\t\tdocument.getElementById(\"city\").disabled = false;\n");
      out.write("\t\t\tdocument.getElementById(\"state\").disabled = false;\n");
      out.write("\t\t\tdocument.getElementById(\"zipcode\").disabled = false;\n");
      out.write("\t\t\tdocument.getElementById(\"email\").disabled = false;\n");
      out.write("\t\t\tdocument.getElementById(\"telephone\").disabled = false;\n");
      out.write("\t\t\tdocument.getElementById(\"registered\").value = null;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<Center>\n");
      out.write("\t\t<b>Welcome!</b>\n");
      out.write("\t</Center>\n");
      out.write("\t<form role=\"form\" data-toggle=\"validator\" name=\"signupForm\"\n");
      out.write("\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/signup\" method=\"POST\">\n");
      out.write("\t\t<p>Profile Information</p>\n");
      out.write("\t\t\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tProfile ID: <input type=\"text\" class=\"form-control\" id=\"profileid\"\n");
      out.write("\t\t\t\tname=\"profileID\" placeholder=\"eg:John123\" required>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tPassword: <input type=\"password\" class=\"form-control\" id=\"pwd\"\n");
      out.write("\t\t\t\tplaceholder=\"Password\" name=\"Password\" required> \n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tConfirm Password: <input type=\"password\" class=\"form-control\" id=\"pwd2\"\n");
      out.write("\t\t\t\tplaceholder=\"Password confirm\" name=\"PasswordConf\" required>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tAge: <input type=\"number\" class=\"form-control\" id=\"age\"\n");
      out.write("\t\t\t\tname=\"age\" min=\"18\" required>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tDating Age Range: \n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\tFrom: <input type=\"number\" class=\"form-control\" id=\"ageRangeStart\"\n");
      out.write("\t\t\t\tname=\"ageRangeStart\" min=\"18\" required>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\tto <input type=\"number\" class=\"form-control\" id=\"ageRangeEnd\"\n");
      out.write("\t\t\t    name=\"ageRangeEnd\" min=\"18\" required>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- private int datingGeoRange; -->\n");
      out.write("\t\t\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tGender: \n");
      out.write("\t\t\t<select class=\"form-control\" id=\"gender\" name=\"gender\" required>\n");
      out.write("\t\t\t\t<option value=\"male\">Male</option>\n");
      out.write("\t\t\t\t<option value=\"female\">Female</option>\n");
      out.write("\t\t\t\t<option value=\"others\">Others</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tHobbies: \n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"hobbies\" name=\"hobbies\" required\n");
      out.write("\t\t\t placeholder=\"please seperate your hobbies by comma(,)\" maxlength=\"1000\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tHeight:\n");
      out.write("\t\t\t<input type=\"number\" step=\"0.01\" id=\"height\" name=\"height\" placeholder=\"eg:1.70\" min = \"0\"> meters\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tWeight:\n");
      out.write("\t\t\t<input type=\"number\" step=\"0.01\" id=\"weight\" name=\"weight\" placeholder=\"eg:56.3\" min = \"0\"> kg\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tHair Color:\n");
      out.write("\t\t\t<input type=\"text\" id=\"hairColor\" name=\"hairColor\" maxlength=\"20\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<p>Basic Information</p>\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"registered\"  id=\"registered\" onclick=\"handleCheck()\" value=\"no\">\n");
      out.write("\t\t\tI have already used this SSN to sign up for this website.<br>\n");
      out.write("\t\t\tWithout checking this, the information below will be updated<br>\n");
      out.write("\t\t\tto all of your profile related to this SSN<br>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tSSN: <input type=\"text\" class=\"form-control\" id=\"ssn\"\n");
      out.write("\t\t\t\tplaceholder=\"Social Security Number\" name=\"SSN\" required>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tFirst Name: <input type=\"text\" class=\"form-control\" id=\"fname\"\n");
      out.write("\t\t\t\tplaceholder=\"First Name\" name=\"FirstName\" required>\n");
      out.write("\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tLast Name: <input type=\"text\" class=\"form-control\" id=\"lname\"\n");
      out.write("\t\t\t\tplaceholder=\"Last Name\" name=\"LastName\" required> \n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tStreet: <input type=\"text\" class=\"form-control\" id=\"street\" name=\"Street\"\n");
      out.write("\t\t\t\tplaceholder=\"Street\" required>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tCity: <input type=\"text\" class=\"form-control\" name=\"City\" id=\"city\"\n");
      out.write("\t\t\t\tplaceholder=\"city\" required>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tState: <input type=\"text\" class=\"form-control\" id=\"state\" name=\"State\"\n");
      out.write("\t\t\t\tplaceholder=\"state\" required>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tZipcode: <input type=\"text\" class=\"form-control\" name=\"Zipcode\" id=\"zipcode\"\n");
      out.write("\t\t\t\tplaceholder=\"zipcode\" required>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- \n");
      out.write("\t\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tCredit Card Number: <input type=\"text\" class=\"form-control\" name=\"CreditCardNo\"\n");
      out.write("\t\t\t\tid=\"creditCardNo\" placeholder=\"creditCardNo\" required>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t -->\n");
      out.write("\t\t\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tEmail: <input type=\"email\" class=\"form-control\" id=\"email\" name=\"Email\"\n");
      out.write("\t\t\t\tplaceholder=\"email\" required> \n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div Class=\"Reg\">\n");
      out.write("\t\t\tPhone Number:<input type=\"text\" class=\"form-control\" id=\"telephone\"\n");
      out.write("\t\t\t\tname=\"Telephone\" placeholder=\"telephone\" required> \n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<input type=\"submit\" name=\"signupBtn\" value=\"Sign Up\"\n");
      out.write("\t\t\tclass=\"btn btn-block sign-up-button\" />\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\t<button type=\"submit\" class=\"btn btn-default pull-left\"\n");
      out.write("\t\tdata-dismiss=\"modal\" onclick=\"window.location.href = 'Signin.jsp'\">\n");
      out.write("\t\t<span class=\"glyphicon glyphicon-remove\"></span> Cancel\n");
      out.write("\t</button>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
